apiVersion: v2
name: delegation-verify-coordinator
description: A Helm chart for the delegation verify coordinator

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: "*"
    repository: "https://charts.bitnami.com/bitnami"
    condition: archive.enablePostgresDB
