# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.1
    hooks:
      - id: helm-docs-container
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=gpt-survey-summarizer

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./../README.md.gotmpl

