# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.1
    hooks:
      - id: helm-docs-built
        args:
          # Comma separated list, no space
          - --chart-to-generate=gpt-survey-summarizer,submission-report,redisinsight

          # The `./` makes it relative to the chart-search-root
          - --template-files=./README.md.gotmpl

