apiVersion: v1
kind: Service
metadata:
  name: {{ include "on-chain-voting.fullname" . }}-web
  labels:
    {{- include "on-chain-voting.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "on-chain-voting.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
