apiVersion: v1
kind: Service
metadata:
  name: {{ include "on-chain-voting.fullname" . }}-server
  labels:
    {{- include "on-chain-voting.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "on-chain-voting.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
