---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-service-backend.fullname" . }}
  labels:
    {{- include "uptime-service-backend.labels" . | nindent 4 }}
data:
  {{- if .Values.deployment.secret.keyspaceCert.override }}
  {{ .Values.deployment.secret.keyspaceCert.name }}: {{ .Values.deployment.secret.keyspaceCert.content | toString | b64enc }}
  {{- end }}
  gcp-sa-json: {{ .Values.deployment.secret.gcpServiceAccount | toString | b64enc }}
