---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-service-backend.fullname" . }}
  labels:
    {{- include "uptime-service-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "uptime-service-backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
