apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-rotation-controller.fullname" . }}
  labels:
    {{- include "pod-rotation-controller.labels" . | nindent 4 }}
data:
  pod-rotation-controller.sh: |
{{ .Files.Get "scripts/pod-rotation-controller.sh" | indent 4 }}
