apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pod-rotation-controller.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
