{{- if .Values.deployment.storeBlocks.aws.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
  labels:
    app: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  gsutil-impersonator.sh: |-
{{ (.Files.Get "scripts/gsutil-impersonator.sh") | indent 4 }}
  gcloud-impersonator.sh: |-
{{ (.Files.Get "scripts/gcloud-impersonator.sh") | indent 4 }}
  s3-blocks-uploader.sh: |-
{{ (.Files.Get "scripts/s3-blocks-uploader.sh") | indent 4 }}
{{- end }}
