---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    testnet: {{ .Values.deployment.testnet }}
    role: {{ default "undefined" .Values.node.role }}
  {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass | quote }}
  {{- end }}
  {{- if .Values.service.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: tcp-p2p
      port: {{ .Values.node.ports.p2p }}
      targetPort: external-port
    {{- if .Values.node.metrics.enabled }}
    - name: metrics-port
      port: {{ .Values.node.metrics.port }}
      targetPort: metrics-port
    {{- end }}
