---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    testnet: {{ .Values.deployment.testnet }}
    role: {{ default "undefined" .Values.node.role }}
  {{- with .Values.service.daemon.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.daemon.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.daemon.type | quote }}
  {{- if .Values.service.daemon.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.daemon.loadBalancerClass | quote }}
  {{- end }}
  {{- if .Values.service.daemon.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ .Values.service.daemon.publishNotReadyAddresses }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: tcp-p2p
      port: {{ .Values.node.ports.p2p }}
      targetPort: external-port
    - name: client
      port: {{ .Values.node.ports.client }}
      targetPort: client-port
    {{- if .Values.node.metrics.enabled }}
    - name: metrics-port
      port: {{ .Values.node.metrics.port }}
      targetPort: metrics-port
    {{- end }}
