{{- if .Values.node.exposeGraphql }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graphql
  labels:
    app: {{ .Release.Name }}
    testnet: {{ .Values.deployment.testnet }}
    role: {{ default "undefined" .Values.node.role }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http-graphql
    protocol: TCP
    port: 80
    targetPort: {{ .Values.node.ports.graphql }}
{{- end }}
