---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "delegation-verify-coordinator.fullname" . }}
  labels:
    {{- include "delegation-verify-coordinator.labels" . | nindent 4 }}
data:
  gcp-sa-json: {{ .Values.secret.gcpServiceAccount | toString | b64enc }}
