{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "delegation-verify-coordinator.serviceAccountName" . }}
  labels:
    app: {{ include "delegation-verify-coordinator.fullname" . }}
  {{- with .Values.serviceAccount.coordinator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
