apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mina-payouts-data-provider.fullname" . }}-ledger-db-query
  labels:
    {{- include "mina-payouts-data-provider.labels" . | nindent 4 }}
data:
  LEDGER_DB_QUERY_USER: {{ .Values.minaPayoutsDataProvider.ledgerDBQuery.user | b64enc }}
  LEDGER_DB_QUERY_PASSWORD: {{ .Values.minaPayoutsDataProvider.ledgerDBQuery.password | b64enc }}
{{- if .Values.minaPayoutsDataProvider.ledgerDBQuery.ssl.enabled }}
  LEDGER_DB_QUERY_CERTIFICATE: {{ .Values.minaPayoutsDataProvider.ledgerDBQuery.ssl.rootCertificate | b64enc }}
{{- end }}
