apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mina-payouts-data-provider.fullname" . }}-block-db-query
  labels:
    {{- include "mina-payouts-data-provider.labels" . | nindent 4 }}
data:
  BLOCK_DB_QUERY_USER: {{ .Values.minaPayoutsDataProvider.blockDBQuery.user | b64enc }}
  BLOCK_DB_QUERY_PASSWORD: {{ .Values.minaPayoutsDataProvider.blockDBQuery.password | b64enc }}
{{- if .Values.minaPayoutsDataProvider.blockDBQuery.ssl.enabled }}
  BLOCK_DB_QUERY_CERTIFICATE: {{ .Values.minaPayoutsDataProvider.blockDBQuery.ssl.rootCertificate | b64enc }}
{{- end }}
