apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mina-payouts-data-provider.fullname" . }}-ledger-db-command
  labels:
    {{- include "mina-payouts-data-provider.labels" . | nindent 4 }}
data:
  LEDGER_DB_COMMAND_USER: {{ .Values.minaPayoutsDataProvider.ledgerDBQuery.user | b64enc }}
  LEDGER_DB_COMMAND_PASSWORD: {{ .Values.minaPayoutsDataProvider.ledgerDBQuery.password | b64enc }}
{{- if .Values.minaPayoutsDataProvider.ledgerDBCommand.ssl.enabled }}
  LEDGER_DB_COMMAND_CERTIFICATE: {{ .Values.minaPayoutsDataProvider.ledgerDBQuery.ssl.rootCertificateBase64 }}
{{- end }}
