apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mina-payouts-data-provider.fullname" . }}-ledger-upload-api
  labels:
    {{- include "mina-payouts-data-provider.labels" . | nindent 4 }}
data:
  LEDGER_UPLOAD_API_USER: {{ .Values.minaPayoutsDataProvider.ledgerUploadAPI.user | b64enc }}
  LEDGER_UPLOAD_API_PASSWORD: {{ .Values.minaPayoutsDataProvider.ledgerUploadAPI.password | b64enc }}
