{{- if .Values.archive.missingBlocksGuardian.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-missing-blocks-guardian
  labels:
    app: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  missing-blocks-guardian.sh: |-
{{ (.Files.Get "scripts/missing-blocks-guardian.sh") | indent 4 }}
{{- end }}
