apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mina-archive.fullname" . }}-scripts
  labels:
    app: {{ include "mina-archive.fullname" . }}
    release: {{ include "mina-archive.fullname" . }}
data:
{{- range $path, $_ :=  .Files.Glob  "scripts/*.sh" }}    
  {{ $path | trimPrefix "scripts/" }}: |- 
    {{ $.Files.Get $path | nindent 4 }}
{{ end }}
