{{- if .Values.archive.dumpCronjob.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          restartPolicy: Never
          containers:
            - name: {{ .Release.Name }}-dump-cronjob
              image: postgres:15-alpine
              env:
                - name: S3_BUCKET
                  value: {{ .Values.archive.dumpCronjob.s3Bucket | quote }}
              command:
                - /bin/bash
                - -c
                - '
                apk add --no-cache aws-cli;
                DATE="$(date +%F_%H%M)";
                FILENAME="{{ .Values.archive.testnet }}-archive-dump-${DATE}".sql;
                pg_dump --no-owner --create {{ tpl .Values.archive.postgresUri . }} > $FILENAME;
                tar -czvf $FILENAME.tar.gz $FILENAME;
                echo "archive database dumped";
                aws s3 cp $FILENAME.tar.gz s3://$S3_BUCKET/$FILENAME.tar.gz;
                echo "archive database uploaded to bucket";
                '
{{- end -}}
