---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
  {{- with .Values.podAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
    test: 'true'
spec:
  replicas: {{ .Values.archive.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        testnet: {{ .Values.archive.testnet }}
        role: archive
      annotations:
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.archive.metrics.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ .Values.archive.metrics.port | quote }}
        prometheus.io/path: '/metrics'
      {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        # Archive Process
        - name: archive
          resources:
            limits:
              memory: {{ .Values.resource.memoryLimit }}
              cpu: {{ .Values.resource.cpuLimit }}
            requests:
              memory: {{ .Values.resource.memoryRequest }}
              cpu: {{ .Values.resource.cpuRequest }}
          image: {{ .Values.archive.image }}
          args: [
            "mina-archive",
            "run",
            {{- if .Values.archive.metrics.enabled }}
            "-metrics-port", "{{ .Values.archive.metrics.port }}",
            {{- end }}
            "-postgres-uri", "{{ tpl .Values.archive.postgresUri . }}",
            {{- if .Values.archive.runtimeConfig }}
            "-config-file", "/config/daemon.json",
            {{- end }}
            "-server-port", "{{ .Values.archive.ports.server }}"
          ]
          env:
          imagePullPolicy: Always
          {{- if .Values.archive.runtimeConfig }}
          volumeMounts:
            - name: {{ .Release.Name }}-runtime-config
              mountPath: "/config/"
          {{- end }}
          ports:
            - name: archive-port
              protocol: TCP
              containerPort: {{ .Values.archive.ports.server }}
            {{- if .Values.archive.metrics.enabled }}
            - name: metrics-port
              protocol: TCP
              containerPort: {{ .Values.archive.metrics.port }}
            {{- end }}
{{- $postgresHost := tpl .Values.archive.postgresHost . }}
{{- $data := dict "postgresHost" $postgresHost "healthcheck" $.Values.healthcheck }}
{{- include "healthcheck.archive.allChecks" $data | indent 10 }}
        {{- if .Values.archive.missingBlocksGuardian.enabled }}
        - name: missing-blocks-guardian
          image: {{ .Values.archive.image }}
          env:
            - name: DB_USERNAME
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: PGPASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: DB_HOST
              value: {{ tpl .Values.archive.postgresHost . | quote }}
            - name: DB_PORT
              value: {{ .Values.archive.ports.postgres | quote }}
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: MINA_NETWORK
              value: {{ .Values.archive.testnet | quote }}
            - name: PRECOMPUTED_BLOCKS_URL
              value: {{ .Values.archive.missingBlocksGuardian.precomputedBlocksURL| quote }}
            - name: MISSING_BLOCKS_GUARDIAN_WAIT_TIME
              value: {{ .Values.archive.missingBlocksGuardian.waitTime| quote }}
          command: ["bash", "-c"]
          args:
            - 'sleep ${MISSING_BLOCKS_GUARDIAN_WAIT_TIME} && bash /scripts/missing-blocks-guardian.sh'
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
          volumeMounts:
            - name: {{ .Release.Name }}-missing-blocks-guardian
              mountPath: "/scripts/"
        {{- end }}
      volumes:
        - name: {{ .Release.Name }}-config-dir
          emptyDir: {}
        {{- if .Values.archive.runtimeConfig }}
        - name: {{ .Release.Name }}-runtime-config
          configMap:
            name: {{ .Release.Name }}-runtime-config
        {{- end }}
        {{- if .Values.archive.missingBlocksGuardian.enabled }}
        - name: {{ .Release.Name }}-missing-blocks-guardian
          configMap:
            name: {{ .Release.Name }}-missing-blocks-guardian
        {{- end }}
