---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- if .Values.archive.service.labels }}
  {{- with .Values.archive.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
    app: {{ .Release.Name }}
    testnet: {{ .Values.archive.testnet }}
  {{- if .Values.archive.service.annotations }}
  {{- with .Values.archive.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  # We want all pods to have their addresses published for the sake of the
  # other testnet pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: tcp-archive
      port: {{ .Values.archive.ports.server }}
      targetPort: archive-port
    {{- if .Values.archive.metrics.enabled }}
    - name: metrics-port
      port: {{ .Values.archive.metrics.port }}
      targetPort: metrics-port
    {{- end }}
