{{- if .Values.node.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mina-archive.fullname" . }}
  labels:
    app: {{ include "mina-archive.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: {{ include "mina-archive.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Values.network }}
  targetLabels:
  - network
{{- end }}
