apiVersion: v1
kind: Service
metadata:
  name: {{ include "redisinsight.fullname" . }}-headless
  labels:
  {{- if .Values.server.headless.labels }}
  {{- with .Values.server.headless.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
    app: {{ include "redisinsight.fullname" . }}
    platform: {{ .Values.platform }}
  {{- if .Values.server.headless.annotations }}
  {{- with .Values.server.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "redisinsight.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-ui
      port: {{ .Values.server.ports.ui }}
      protocol: TCP
      targetPort: http-ui
