deployment:
  image:
    repository: 673156464838.dkr.ecr.us-west-2.amazonaws.com/block-producers-uptime
    pullPolicy: IfNotPresent
    tag: "1.2.0-test-1"
  replicaCount: 1
  network:
    name:
    platform:
  secrets:
    credentialFile:
      name: "block-producers-uptime-gcp-sa-credential"
      dir:
      path:
      content:
  awsConfig:
    network:
    sheetId:
    region:
    accountId:
  gcpStaging:
    enabled:
resources:
  memoryRequest: "256Mi"
  cpuRequest: "500m"
  memoryLimit: "512Mi"
  cpuLimit: "1"

service:
  type: ClusterIp
  port: 8080

cron:
  schedule: "59 11,23 * * *" # This must be a string in quotes

ingress:
  class: alb
  annotations: {}
  hosts: {}

serviceaccount:
  annotations: {}
