{{ if .Values.deployment.analyzerScriptConfig.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-sheets
  labels:
    app: {{ .Release.Name }}-sheets
spec:
  schedule: {{ .Values.cron.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          containers:
          - name: {{ .Release.Name }}-sheets
            image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tagSheets }}"
            imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
            command:
            - itn_uptime_analyzer
            env:
              {{- if .Values.deployment.secrets.credentialFile.path }}
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: {{ .Values.deployment.secrets.credentialFile.path }}
              {{- end }}
              {{- if .Values.deployment.gcpStaging.enabled }}
              - name: TEST
                value: {{ .Values.deployment.gcpStaging.enabled | quote }}
              {{- end }}
              {{- with .Values.deployment.awsConfig }}
              - name: CONFIG_NETWORK_NAME
                value: {{ .network | quote }}
              - name: CONFIG_AWS_REGION
                value: {{ .region | quote }}
              - name: CONFIG_AWS_ACCOUNT_ID
                value: {{ .accountId | quote }}
              {{- end }}
              {{- with .Values.deployment.analyzerScriptConfig }}
              - name: CONFIG_ANALYZER_OUTPUT_GSHEET_ID
                value: {{ .outputSheetId | quote }}
              - name: CONFIG_STDOUT
                value: {{ .stdout | quote }}
              - name: CONFIG_LOCAL_OUTPUT
                value: {{ .localOutput | quote }}
              - name: CONFIG_S3_BUCKET
                value: {{ .s3bucket | quote }}
              - name: CONFIG_S3_KEY
                value: {{ .s3key | quote }}
              {{- if .periodStart }}
              - name: CONFIG_PERIOD_START
                value: {{ .periodStart | quote }}
              {{- end }}
              {{- if .periodEnd }}
              - name: CONFIG_PERIOD_END
                value: {{ .periodEnd | quote }}
              {{- end }}
              {{- if .periodInterval }}
              - name: CONFIG_PERIOD_INTERVAL
                value: {{ .periodInterval | quote }}
              {{- end }}
              - name: CONFIG_IGNORE_IPS
                value: {{ .ignoreIps | quote }}
              {{- end }}
              {{- with .Values.deployment.whitelistConfig }}
              - name: CONFIG_GSHEET_ID
                value: {{ .sheetId | quote }}
              - name: DELEGATION_WHITELIST_LIST
                value: {{ .list | quote }}
              - name: DELEGATION_WHITELIST_COLUMN
                value: {{ .column | quote }}
              {{- end }}
            volumeMounts:
              {{- with .Values.deployment.secrets.credentialFile }}
              - name:  {{ .releaseName }}-credential-file
                mountPath: {{ .dir | quote }}
              {{- end }}
          volumes:
            {{- with .Values.deployment.secrets.credentialFile }}
            - name: {{ .releaseName }}-credential-file
              secret:
                secretName: {{ .releaseName }}
                defaultMode: 0600
                items:
                  - key: {{ .name }}
                    path: {{ .name }}.json
            {{- end }}
          restartPolicy: OnFailure
{{- end }}
