apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cron.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          containers:
          - name: {{ .Release.Name }}
            image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
            imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
            command:
            - itn_uptime_analyzer
            env:
              {{- if .Values.deployment.secrets.credentialFile.path }}
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: {{ .Values.deployment.secrets.credentialFile.path }}
              {{- end }}
              {{- if .Values.deployment.gcpStaging.enabled }}
              - name: TEST
                value: {{ .Values.deployment.gcpStaging.enabled | quote }}
              {{- end }}
              {{- with .Values.deployment.awsConfig }}
              - name: CONFIG_NETWORK_NAME
                value: {{ .network | quote }}
              - name: CONFIG_GSHEET_ID
                value: {{ .sheetId | quote }}
              - name: CONFIG_AWS_REGION
                value: {{ .region | quote }}
              - name: CONFIG_AWS_ACCOUNT_ID
                value: {{ .accountId | quote }}
              - name: CONFIG_ANALYZER_OUTPUT_GSHEET_ID
                value: {{ .analyzerOutputSheetId | quote }}
              {{- end }}
            volumeMounts:
              {{- with .Values.deployment.secrets.credentialFile }}
              - name:  {{ .releaseName }}-credential-file
                mountPath: {{ .dir | quote }}
              {{- end }}
          volumes:
            {{- with .Values.deployment.secrets.credentialFile }}
            - name: {{ .releaseName }}-credential-file
              secret:
                secretName: {{ .releaseName }}
                defaultMode: 0600
                items:
                  - key: {{ .name }}
                    path: {{ .name }}.json
            {{- end }}
          restartPolicy: OnFailure
