apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpt-survey-summarizer.fullname" . }}-bot
  labels:
    {{- include "gpt-survey-summarizer.labels" . | nindent 4 }}-bot
spec:
  replicas: {{ .Values.bot.replicaCount }}
  selector:
    matchLabels:
      {{- include "gpt-survey-summarizer.selectorLabels" . | nindent 6 }}-bot
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gpt-survey-summarizer.selectorLabels" . | nindent 8 }}-bot
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gpt-survey-summarizer.serviceAccountName" . }}-bot
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: bot
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.bot.args | nindent 12 }}
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "gpt-survey-summarizer.fullname" . }}
                  key: discordToken
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "gpt-survey-summarizer.fullname" . }}
                  key: discordClientId
            - name: GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "gpt-survey-summarizer.fullname" . }}
                  key: discordGuildId
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "gpt-survey-summarizer.fullname" . }}
                  key: redisUrl
          {{- if .Values.bot.extraEnvVars }}
            {{- toYaml .Values.bot.extraEnvVars | nindent 12 }}
          {{- end }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
