apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpt-survey-summarizer.fullname" . }}
data:
  openAiApiKey: {{ .Values.config.openAiApiKey | b64enc }}
  discordClientId: {{ .Values.config.discord.clientId | b64enc }}
  discordGuildId: {{ .Values.config.discord.guildId | b64enc }}
  discordToken: {{ .Values.config.discord.token | b64enc }}
