{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpt-survey-summarizer.serviceAccountName" . }}-server
  labels:
    {{- include "gpt-survey-summarizer.labels" . | nindent 4 }}-server
  {{- with .Values.server.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
