{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpt-survey-summarizer.serviceAccountName" . }}-database-dump-exporter
  labels:
    {{- include "gpt-survey-summarizer.labels" . | nindent 4 }}-database-dump-exporter
  {{- with .Values.databaseDumpExporter.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
