{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpt-survey-summarizer.serviceAccountName" . }}-bot
  labels:
    {{- include "gpt-survey-summarizer.labels" . | nindent 4 }}-bot
  {{- with .Values.bot.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
