{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpt-survey-summarizer.serviceAccountName" . }}-dump
  labels:
    {{- include "gpt-survey-summarizer.labels" . | nindent 4 }}-dump
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
