deployment:
  testnet: "berkeley"
  image: minaprotocol/mina-daemon:1.3.2beta2-release-2.0.0-05c2f73-bulseye-berkeley
  genesisLedgerURL:
  customEntrypoint:
    enabled: true
    entrypoint: "mina"
  peerListURL: "https://storage.googleapis.com/seed-lists/berkeley_seeds.txt"
  uptime:
    enabled: false
    url:
  seedPeers:
    - /dns4/seed-1.berkeley.o1test.net/tcp/10000/p2p/12D3KooWAdgYL6hv18M3iDBdaK1dRygPivSfAfBNDzie6YqydVbs
    - /dns4/seed-2.berkeley.o1test.net/tcp/10001/p2p/12D3KooWLjs54xHzVmMmGYb7W5RVibqbwD1co7M2ZMfPgPm7iAag
    - /dns4/seed-3.berkeley.o1test.net/tcp/10002/p2p/12D3KooWEiGVAFC7curXWXiGZyMWnZK9h8BKr88U8D5PKV3dXciv
  storeBlocks:
    enabled: false
    filename: precomputed_blocks.json
    directory: /blocks
    storageClass:
    sizePVC: 5Gi

node:
  name: "berkeley-node"
  role:
  replicas: 1
  fullname: "berkeley-node"
  loadBalancer:
    enabled: false
    ip: "auto"
  exposeGraphql: false
  exposeP2P:
  logLevel: Info
  fileLogLevel: Error
  generateGenesisProof: true
  maxConnections: 200
  snarkWorkerFee:
  allPeersSeenMetric:
  archiveRocksDB:
  background:
  bindIP:
  contactInfo:
  currentProtocolVersion:
  demoMode:
  directPeer:
  disableNodeStatus:
  enableFlooding:
  enablePeerExchange: true
  externalIP:
  fileLogRotations:
  gcStatInterval:
  internalTracing:
  isolateNetwork:
  itnGraphQLPort:
  itnKeys:
  itnMaxLogs:
  libp2pMetricsPort:
  limitedGraphQLPort:
  logBlockCreation:
  logPrecomputedBlocks:
  logSnarkWorkGossip: true
  logTxnPoolGossip: true
  minConnections:
  minBlockReward:
  noSuperCatchup:
  openLimitedGraphQLPort:
  peer:
  peerListFile:
  peerListURL:
  peerProtectionRate:
  precomputedBlocksFile:
  proofLevel:
  proposedProtocolVersion:
  snarkWorkerParallelism:
  stopTime:
  tracing:
  uploadBlocksToGoogleCloud:
  uploadSubmitterKey:
  uploadSubmitterPubkey:
  validationQueueSize:
  workReassignmentWait:
  workSelection:
  metrics:
    enabled: false
    port: 10001
  ports:
    client: 8301
    graphql: 3085
    p2p: 10801
  statsUrl:
  errorsUrl:
  archive:
    enabled: false
    address: staging-berkeley-archive:3086
  libp2pKeys:
    enabled: true
    legacy: false
  walletKeys:
    enabled: false
  daemonMode:
    blockProducer: false
    snarkWorker: false
    coordinator: false
    seed: false
  secrets:
    walletPassword: ""
    libp2pPassword: ""
    walletKey: ""
    walletPub: ""
    discoveryLibp2p: ""
    discoveryLibp2pPeerid: ""

serviceAccount:
  annotations: {}

ingress:
  enabled: false
  labels: {}
  annotations: {}
  className: ""
  tls: false
  hosts: []
    # - host: chart-example.local
    #   paths: []
    #    - path: /
    #      pathType: Prefix
    #      backend:
    #        service:
    #          name: chart-example.local
    #          port: 8080

podAnnotations: {}

resources:
  memoryRequest: "16.0Gi"
  cpuRequest: "4"
  memoryLimit: "16.0Gi"
  cpuLimit: "8"

healthcheck:
  enabled: true
  startup:
    periodSeconds: 30
    failureThreshold: 30
  failureThreshold: 10
  periodSeconds: 5
  initialDelaySeconds: 10
  timeoutSeconds: 60
