name: pre-commit

on:
  pull_request:
  push:
    branches: [main, jm-test-PM-1643-pre-commit-ci]

jobs:
  pre-commit:
    runs-on: minafoundation-default-runners
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
