apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "delegation-program-payouts.fullname" . }}
  labels:
    {{- include "delegation-program-payouts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "delegation-program-payouts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "delegation-program-payouts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "delegation-program-payouts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.payouts.appName }}
            - name: APP_NAME
              value: {{ .Values.payouts.appName | quote }}
            {{- end }}
            {{- if .Values.payouts.appEnv }}
            - name: APP_ENV
              value: {{ .Values.payouts.appEnv | quote }}
            {{- end }}
            {{- if .Values.payouts.appKey }}
            - name: APP_KEY
              value: {{ .Values.payouts.appKey | quote }}
            {{- end }}
            {{- if .Values.payouts.appDebug }}
            - name: APP_DEBUG
              value: {{ .Values.payouts.appDebug | quote }}
            {{- end }}
            {{- if .Values.payouts.appUrl }}
            - name: APP_URL
              value: {{ .Values.payouts.appUrl | quote }}
            {{- end }}
            {{- if .Values.payouts.minaGraphQLEndpoint }}
            - name: MINA_GRAPHQL_ENDPOINT
              value: {{ .Values.payouts.minaGraphQLEndpoint | quote }}
            {{- end }}
            {{- if .Values.payouts.burnWalletAddress }}
            - name: BURN_WALLET_ADDRESS
              value: {{ .Values.payouts.burnWalletAddress | quote }}
            {{- end }}
            {{- if .Values.payouts.advancedPayoutDebug }}
            - name: ADVANCED_PAYOUT_DEBUG
              value: {{ .Values.payouts.advancedPayoutDebug | quote }}
            {{- end }}
            {{- if .Values.payouts.defaultCommissionRate }}
            - name: DEFAULT_COMMISSION_RATE
              value: {{ .Values.payouts.defaultCommissionRate | quote }}
            {{- end }}
            {{- if .Values.payouts.logChannel }}
            - name: LOG_CHANNEL
              value: {{ .Values.payouts.logChannel | quote }}
            {{- end }}
            {{- if .Values.payouts.logDeprecationsChannel }}
            - name: LOG_DEPRECATIONS_CHANNEL
              value: {{ .Values.payouts.logDeprecationsChannel | quote }}
            {{- end }}
            {{- if .Values.payouts.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.payouts.logLevel | quote }}
            {{- end }}
            {{- if .Values.payouts.payoutsDbConnection }}
            - name: DB_CONNECTION
              value: {{ .Values.payouts.payoutsDbConnection | quote }}
            {{- end }}
            {{- if .Values.payouts.payoutsDbHost }}
            - name: DB_HOST
              value: {{ .Values.payouts.payoutsDbHost | quote }}
            {{- end }}
            {{- if .Values.payouts.payoutsDbPort }}
            - name: DB_PORT
              value: {{ .Values.payouts.payoutsDbPort | quote }}
            {{- end }}
            {{- if .Values.payouts.payoutsDbDatabase }}
            - name: DB_DATABASE
              value: {{ .Values.payouts.payoutsDbDatabase | quote }}
            {{- end }}
            {{- if .Values.payouts.payoutsDbUsername }}
            - name: DB_USERNAME
              value: {{ .Values.payouts.payoutsDbUsername | quote }}
            {{- end }}
            {{- if .Values.payouts.payoutsDbPassword }}
            - name: DB_PASSWORD
              value: {{ .Values.payouts.payoutsDbPassword | quote }}
            {{- end }}
            {{- if .Values.payouts.archiveDbConnection }}
            - name: ARCHIVE_DB_CONNECTION
              value: {{ .Values.payouts.archiveDbConnection | quote }}
            {{- end }}
            {{- if .Values.payouts.archiveDbHost }}
            - name: ARCHIVE_DB_HOST
              value: {{ .Values.payouts.archiveDbHost | quote }}
            {{- end }}
            {{- if .Values.payouts.archiveDbPort }}
            - name: ARCHIVE_DB_PORT
              value: {{ .Values.payouts.archiveDbPort | quote }}
            {{- end }}
            {{- if .Values.payouts.archiveDbDatabase }}
            - name: ARCHIVE_DB_DATABASE
              value: {{ .Values.payouts.archiveDbDatabase | quote }}
            {{- end }}
            {{- if .Values.payouts.archiveDbUsername }}
            - name: ARCHIVE_DB_USERNAME
              value: {{ .Values.payouts.archiveDbUsername | quote }}
            {{- end }}
            {{- if .Values.payouts.archiveDbPassword }}
            - name: ARCHIVE_DB_PASSWORD
              value: {{ .Values.payouts.archiveDbPassword | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/wallets
              port: http
          readinessProbe:
            httpGet:
              path: /api/wallets
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
